#pragma once

#define MK_KINETIC_SPEED

#define MOUSEKEY_INTERVAL 16

#define MOUSEKEY_DELAY 0

#define MOUSEKEY_MOVE_DELTA 16

#define MOUSEKEY_INITIAL_SPEED 400

#define MOUSEKEY_BASE_SPEED 7200 

#define MOUSEKEY_DECELERATED_SPEED	800

#define MOUSEKEY_ACCELERATED_SPEED	2200
